package com.ahnis.journalai.analysis.service;

import com.ahnis.journalai.analysis.dto.MoodReportApiResponse;
import com.ahnis.journalai.analysis.dto.MoodReportEmailResponse;
import com.ahnis.journalai.analysis.entity.MoodReportEntity;
import com.ahnis.journalai.analysis.exception.ReportNotFoundException;
import com.ahnis.journalai.analysis.mapper.ReportMapper;
import com.ahnis.journalai.analysis.repository.ReportRepository;
import com.ahnis.journalai.notification.service.NotificationService;
import com.ahnis.journalai.user.entity.User;
import lombok.extern.slf4j.Slf4j;
import org.bson.types.ObjectId;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.List;

@Slf4j
@Service
public class ReportService {
    private final JournalAnalysisService journalAnalysisService;
    private final ReportRepository reportRepository;
    private final NotificationService notificationService;
    private final ReportMapper reportMapper;

    public ReportService(JournalAnalysisService journalAnalysisService, ReportRepository reportRepository, NotificationService notificationService,
                         ReportMapper reportMapper) {
        this.journalAnalysisService = journalAnalysisService;
        this.reportRepository = reportRepository;
        this.notificationService = notificationService;
        this.reportMapper = reportMapper;
    }

    @Async
    public void sendReport(User user, MoodReportEmailResponse report) {
        log.info("Sending report to user: {}", user.getUsername());
        notificationService.sendEmailReport(user.getEmail(), report);
    }

    @Async
    @Transactional
    public void generateReport(User user, Instant startDate, Instant endDate) {
        try {
            // Analyze journals between startDate and endDate
            MoodReportEmailResponse moodReport = journalAnalysisService.analyzeUserMood(user.getId(), user.getUsername(), user.getPreferences(), startDate, endDate).join();

            // Save the report
            var reportEntity = reportMapper.toMoodReportEntity(user, moodReport);
            reportRepository.save(reportEntity);


            this.sendReport(user, moodReport);
            log.info("Report generated by method2 of reportService and saved for user: {}", user.getUsername());
        } catch (Exception e) {
            log.error("Failed to generate report for user: {}", user.getUsername(), e);
            throw new RuntimeException("Failed to generate report", e);
        }
    }

    public Page<MoodReportApiResponse> getAllReportsByUserId(String userId, int page, int size) {
        Pageable pageable = PageRequest.of(page, size, Sort.by(Sort.Direction.DESC, "createdAt")); // Optional sort
        Page<MoodReportEntity> reportPage = reportRepository.findByUserId(userId, pageable);
        return reportPage.map(reportMapper::toApiResponse);
    }


    public MoodReportApiResponse getReportById(String userId, String reportId) {
        return reportRepository.findByIdAndUserId(reportId, userId)
                .map(reportMapper::toApiResponse)
                .orElseThrow(() -> new ReportNotFoundException("Report Not found {report id %s , user id %s} ".formatted(reportId, userId)));

    }

    public MoodReportApiResponse getLatestReportByUserId(String userId) {
        return reportRepository.findFirstByUserIdOrderByReportDateDesc(userId)
                .map(reportMapper::toApiResponse)
                .orElseThrow(() -> new ReportNotFoundException("No reports found for %s userId".formatted(userId)));
    }
}
